using System.Globalization;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace BenjaminAbt.AssemblyMetadata.UnitTests;

/// <summary>
/// Tests that exercise the <see cref="AssemblyMetadataGenerator"/> code paths at runtime
/// via <see cref="CSharpGeneratorDriver"/>.
/// </summary>
/// <remarks>
/// <para>
/// These tests instantiate the generator and run it against an in-memory
/// <see cref="CSharpCompilation"/>, making the generator's <c>Initialize</c>, <c>Execute</c>,
/// and <c>BuildSource</c> methods execute at test runtime. This approach achieves full code
/// coverage of the generator class itself, which otherwise only runs at build/compile time.
/// </para>
/// <para>
/// For tests that validate the <em>values</em> baked into the compiled test binary, see
/// <see cref="AssemblyMetadataInfoTests"/>.
/// </para>
/// </remarks>
public partial class AssemblyMetadataGeneratorTests
{
    // ── Helpers ─────────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Creates a minimal in-memory C# compilation used to host the generator under test.
    /// Only <c>System.Private.CoreLib</c> (via <c>typeof(object)</c>) is referenced because
    /// the generated source only uses primitive types (<c>string</c>, <c>long</c>, <c>int</c>).
    /// </summary>
    private static CSharpCompilation CreateEmptyCompilation() =>
        CSharpCompilation.Create(
            assemblyName: "TestAssembly",
            syntaxTrees: [],
            references: [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)],
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

    /// <summary>
    /// Runs the <see cref="AssemblyMetadataGenerator"/> against an empty compilation and
    /// returns the <see cref="GeneratorDriverRunResult"/> for inspection.
    /// Uses <see cref="TestContext.Current"/> cancellation token for responsive cancellation.
    /// </summary>
    private static GeneratorDriverRunResult RunGenerator()
    {
        CSharpGeneratorDriver driver = CSharpGeneratorDriver.Create(new AssemblyMetadataGenerator());
        return driver
            .RunGenerators(CreateEmptyCompilation(), TestContext.Current.CancellationToken)
            .GetRunResult();
    }

    // ── Output structure ────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Verifies the generator emits exactly one source file - no more, no less.
    /// </summary>
    [Fact]
    public void Generator_ProducesExactlyOneGeneratedFile()
    {
        GeneratorDriverRunResult result = RunGenerator();
        Assert.Single(result.GeneratedTrees);
    }

    /// <summary>
    /// Verifies the generated file uses the expected hint name <c>AssemblyMetadataInfo.gen.cs</c>.
    /// This name is used by Roslyn to construct the in-memory file path and by IDEs for navigation.
    /// </summary>
    [Fact]
    public void Generator_GeneratedFile_HasExpectedHintName()
    {
        GeneratorDriverRunResult result = RunGenerator();
        string filePath = result.GeneratedTrees[0].FilePath;
        Assert.EndsWith("AssemblyMetadataInfo.gen.cs", filePath, StringComparison.Ordinal);
    }

    /// <summary>
    /// Verifies the generator itself emits no <see cref="Diagnostic"/> objects.
    /// Generator diagnostics indicate structural errors in the generator's own logic.
    /// </summary>
    [Fact]
    public void Generator_ProducesNoDiagnostics()
    {
        GeneratorDriverRunResult result = RunGenerator();
        Assert.Empty(result.Diagnostics);
    }

    // ── Generated source content ────────────────────────────────────────────────────────────

    /// <summary>
    /// Verifies the generated source begins with <c>// &lt;auto-generated /&gt;</c>, which
    /// signals Roslyn and other tools that the file is machine-generated and should be excluded
    /// from additional analyzer warnings.
    /// </summary>
    [Fact]
    public void Generator_GeneratedSource_HasAutoGeneratedHeader()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("// <auto-generated />", source, StringComparison.Ordinal);
    }

    /// <summary>
    /// Verifies the generated source is placed inside the expected
    /// <c>BenjaminAbt.AssemblyMetadata</c> namespace.
    /// </summary>
    [Fact]
    public void Generator_GeneratedSource_HasCorrectNamespace()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("namespace BenjaminAbt.AssemblyMetadata", source, StringComparison.Ordinal);
    }

    /// <summary>
    /// Verifies the generated source declares the outer <c>AssemblyMetadataInfo</c> class.
    /// </summary>
    [Fact]
    public void Generator_GeneratedSource_HasAssemblyMetadataInfoClass()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("class AssemblyMetadataInfo", source, StringComparison.Ordinal);
    }

    /// <summary>
    /// Verifies the generated source declares the nested <c>BuildInfo</c> class.
    /// </summary>
    [Fact]
    public void Generator_GeneratedSource_HasBuildInfoClass()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("class BuildInfo", source, StringComparison.Ordinal);
    }

    /// <summary>Verifies the <c>BuildTimestamp</c> constant is declared.</summary>
    [Fact]
    public void Generator_GeneratedSource_HasBuildTimestampConst()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("public const string BuildTimestamp", source, StringComparison.Ordinal);
    }

    /// <summary>Verifies the <c>BuildFileTimeUtc</c> constant is declared.</summary>
    [Fact]
    public void Generator_GeneratedSource_HasBuildFileTimeUtcConst()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("public const long BuildFileTimeUtc", source, StringComparison.Ordinal);
    }

    /// <summary>Verifies the <c>BuildDateYear</c> constant is declared.</summary>
    [Fact]
    public void Generator_GeneratedSource_HasBuildDateYearConst()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("public const int BuildDateYear", source, StringComparison.Ordinal);
    }

    /// <summary>Verifies the <c>BuildDateMonth</c> constant is declared.</summary>
    [Fact]
    public void Generator_GeneratedSource_HasBuildDateMonthConst()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("public const int BuildDateMonth", source, StringComparison.Ordinal);
    }

    /// <summary>Verifies the <c>BuildDateDay</c> constant is declared.</summary>
    [Fact]
    public void Generator_GeneratedSource_HasBuildDateDayConst()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("public const int BuildDateDay", source, StringComparison.Ordinal);
    }

    /// <summary>Verifies the <c>BuildTimeHour</c> constant is declared.</summary>
    [Fact]
    public void Generator_GeneratedSource_HasBuildTimeHourConst()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("public const int BuildTimeHour", source, StringComparison.Ordinal);
    }

    /// <summary>Verifies the <c>BuildTimeMinute</c> constant is declared.</summary>
    [Fact]
    public void Generator_GeneratedSource_HasBuildTimeMinuteConst()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("public const int BuildTimeMinute", source, StringComparison.Ordinal);
    }

    /// <summary>Verifies the <c>BuildTimeSecond</c> constant is declared.</summary>
    [Fact]
    public void Generator_GeneratedSource_HasBuildTimeSecondConst()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Assert.Contains("public const int BuildTimeSecond", source, StringComparison.Ordinal);
    }

    // ── Value semantics ─────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Verifies that the emitted <c>BuildTimestamp</c> value is a valid ISO 8601 round-trip
    /// string parseable with the <c>"o"</c> format specifier.
    /// </summary>
    [Fact]
    public void Generator_BuildTimestamp_IsValidIso8601()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Match match = BuildTimestampRegex().Match(source);
        Assert.True(match.Success, "BuildTimestamp value not found in generated source.");

        // ParseExact throws if the format is wrong - no explicit Assert needed
        DateTimeOffset parsed = DateTimeOffset.ParseExact(match.Groups["val"].Value, "o", null);
        Assert.Equal(TimeSpan.Zero, parsed.Offset); // generator must always emit UTC
    }

    /// <summary>
    /// Verifies that the emitted <c>BuildFileTimeUtc</c> value is a positive long, representing a
    /// valid Windows FileTime after the epoch 1601-01-01T00:00:00Z.
    /// </summary>
    [Fact]
    public void Generator_BuildFileTime_IsPositive()
    {
        string source = RunGenerator().GeneratedTrees[0].ToString();
        Match match = BuildFileTimeRegex().Match(source);
        Assert.True(match.Success, "BuildFileTimeUtc value not found in generated source.");

        long fileTime = long.Parse(match.Groups["val"].Value, CultureInfo.InvariantCulture);
        Assert.True(fileTime > 0);
    }

    /// <summary>
    /// Verifies that all eight emitted constants are internally consistent: the timestamp,
    /// FileTime, year, month, day, hour, minute, and second must all refer to the same instant.
    /// </summary>
    /// <remarks>
    /// This is the key correctness test for <c>BuildSource</c>: it confirms that every constant
    /// is derived from the same <see cref="DateTimeOffset"/> captured in a single call,
    /// with no off-by-one or formatting errors.
    /// </remarks>
    [Fact]
    public void Generator_BuildTimestamp_IsConsistentWithAllComponents()
    {
        // Run the generator once; extract all eight values from the same emitted source
        // to verify the internal consistency of the BuildSource method.
        string source = RunGenerator().GeneratedTrees[0].ToString();

        string ts = BuildTimestampRegex().Match(source).Groups["val"].Value;
        long ft = long.Parse(BuildFileTimeRegex().Match(source).Groups["val"].Value,
            CultureInfo.InvariantCulture);
        int year = int.Parse(BuildDateYearRegex().Match(source).Groups["val"].Value,
            CultureInfo.InvariantCulture);
        int month = int.Parse(BuildDateMonthRegex().Match(source).Groups["val"].Value,
            CultureInfo.InvariantCulture);
        int day = int.Parse(BuildDateDayRegex().Match(source).Groups["val"].Value,
            CultureInfo.InvariantCulture);
        int hour = int.Parse(BuildTimeHourRegex().Match(source).Groups["val"].Value,
            CultureInfo.InvariantCulture);
        int minute = int.Parse(BuildTimeMinuteRegex().Match(source).Groups["val"].Value,
            CultureInfo.InvariantCulture);
        int second = int.Parse(BuildTimeSecondRegex().Match(source).Groups["val"].Value,
            CultureInfo.InvariantCulture);

        DateTimeOffset buildOn = DateTimeOffset.ParseExact(ts, "o", null);

        Assert.Equal(ft, buildOn.ToFileTime());
        Assert.Equal(year, buildOn.Year);
        Assert.Equal(month, buildOn.Month);
        Assert.Equal(day, buildOn.Day);
        Assert.Equal(hour, buildOn.Hour);
        Assert.Equal(minute, buildOn.Minute);
        Assert.Equal(second, buildOn.Second);
    }

    // ── Compilation correctness ─────────────────────────────────────────────────────────────

    /// <summary>
    /// Verifies that the generated C# source compiles without any errors when added to a
    /// <see cref="CSharpCompilation"/>. This catches syntax mistakes or invalid identifiers
    /// that could be introduced by changes to the source-building logic.
    /// </summary>
    [Fact]
    public void Generator_GeneratedSource_ProducesNoCompilationErrors()
    {
        CSharpCompilation compilation = CreateEmptyCompilation();
        CSharpGeneratorDriver driver = CSharpGeneratorDriver.Create(new AssemblyMetadataGenerator());

        driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out Compilation updatedCompilation,
            out _,
            TestContext.Current.CancellationToken);

        System.Collections.Generic.IEnumerable<Diagnostic> errors = updatedCompilation
            .GetDiagnostics(TestContext.Current.CancellationToken)
            .Where(d => d.Severity == DiagnosticSeverity.Error);

        Assert.Empty(errors);
    }

    // ── Source-generated regex patterns (avoids MA0009 ReDoS false-positives) ──────────────

    /// <summary>Matches the <c>BuildTimestamp</c> string literal in generated source.</summary>
    [GeneratedRegex(@"BuildTimestamp = ""(?<val>[^""]+)""", RegexOptions.NonBacktracking | RegexOptions.ExplicitCapture)]
    private static partial Regex BuildTimestampRegex();

    /// <summary>Matches the <c>BuildFileTimeUtc</c> numeric literal in generated source.</summary>
    [GeneratedRegex(@"BuildFileTimeUtc = (?<val>\d+)L", RegexOptions.NonBacktracking | RegexOptions.ExplicitCapture)]
    private static partial Regex BuildFileTimeRegex();

    /// <summary>Matches the <c>BuildDateYear</c> integer literal in generated source.</summary>
    [GeneratedRegex(@"BuildDateYear = (?<val>\d+)", RegexOptions.NonBacktracking | RegexOptions.ExplicitCapture)]
    private static partial Regex BuildDateYearRegex();

    /// <summary>Matches the <c>BuildDateMonth</c> integer literal in generated source.</summary>
    [GeneratedRegex(@"BuildDateMonth = (?<val>\d+)", RegexOptions.NonBacktracking | RegexOptions.ExplicitCapture)]
    private static partial Regex BuildDateMonthRegex();

    /// <summary>Matches the <c>BuildDateDay</c> integer literal in generated source.</summary>
    [GeneratedRegex(@"BuildDateDay = (?<val>\d+)", RegexOptions.NonBacktracking | RegexOptions.ExplicitCapture)]
    private static partial Regex BuildDateDayRegex();

    /// <summary>Matches the <c>BuildTimeHour</c> integer literal in generated source.</summary>
    [GeneratedRegex(@"BuildTimeHour = (?<val>\d+)", RegexOptions.NonBacktracking | RegexOptions.ExplicitCapture)]
    private static partial Regex BuildTimeHourRegex();

    /// <summary>Matches the <c>BuildTimeMinute</c> integer literal in generated source.</summary>
    [GeneratedRegex(@"BuildTimeMinute = (?<val>\d+)", RegexOptions.NonBacktracking | RegexOptions.ExplicitCapture)]
    private static partial Regex BuildTimeMinuteRegex();

    /// <summary>Matches the <c>BuildTimeSecond</c> integer literal in generated source.</summary>
    [GeneratedRegex(@"BuildTimeSecond = (?<val>\d+)", RegexOptions.NonBacktracking | RegexOptions.ExplicitCapture)]
    private static partial Regex BuildTimeSecondRegex();
}

